### ISSUE TITLE
Permission Request

### ISSUE THREAD

**Issue by yankejustin** [gmamaladze/globalmousekeyhook#16]
Sorry to be somewhat irrelevant here, but I would greatly appreciate using a few portions of your code in a project I enjoy working with. The project is a Remote Administration Tool and has various neat little features. We have recently started a Keylogger and it is a very daunting and difficult task (so many little exceptions to handling keys!). Our tool is by MaxXor and is named xRAT.
Credit is always given where credit is due. I would just like to know if obtaining some of the source is a possibility with the intent that it will likely be modified to suit our needs.
Please let me know what you think about this situation.

Thank you.

**Comment by rabbitsmith** [comment]
i support this.

**Comment by gmamaladze** [comment]
This code is distributed under [MIT License](https://github.com/gmamaladze/globalmousekeyhook/blob/vNext/LICENSE.txt).

This means basically, you can do whatever you want as long as you **include the original copyright and license notice** in any copy of the software/source.

**Nevertheless**: I would advice following:
* Use [NuGet package](https://www.nuget.org/packages/MouseKeyHook) as component without cutting out parts of code. This wil allow you to benefit from updates and bug-fixes without digging into the code again.
* If you want tu cut and modify because you require features which are not available you have two options:
  * Request the feature by creating an issue.
  * [Fork & pull](https://help.github.com/articles/using-pull-requests/) - so you can implement the feature yourself - I'm going to review it and put into the product.

**Comment by yankejustin** [comment]
I appreciate the response. :)
